POST    http://localhost:3000/api/users
Content-Type: application/json


{

        "fname":"ali",
        "lname":"ali",
        "email":"zeal@gmail.com",
        "password":"ali",
        "orgname":"abc"
}


###
POST   http://localhost:3000/api/auth/login
Content-Type: application/json


{
       
        "name":"ali",
        "email":"zeal@gmail.com",
        "password":"ali"
}

######
GET    http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMmIzOGYzYjktMzE5MC00MmNiLWJkODUtY2UxNjVmNTFiMWQ5IiwidXNlcl9lbWFpbCI6InplYWxAZ21haWwuY29tIiwiaWF0IjoxNzIzODQyMzM4LCJleHAiOjE3MjM4NDIzNTh9.l9348W-trypQU0a37XEd9XfxxPgRiGuBuEXtklLk0Dk

###
GET   http://localhost:3000/api/auth/refresh_token

### 
DELETE  http://localhost:3000/api/auth/refresh_token